AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  ftp2s3:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::956478571341:role/AWSLambdaAccess2S3'
      Environment:
        Variables:
          FTP_DIRECTORY: pub/example/
          FTP_HOST: test.rebex.net
          FTP_PASSWORD: password
          FTP_PORT: '21'
          FTP_USERNAME: demo
          S3_BUCKET: ftp-sink
      Tags:
        Scope: ftp2s3
      RuntimePolicy:
        UpdateRuntimeOn: Auto
